#pragma once
#include "Scenegraph.h"
#include <iostream>
/**
The class "Level" has a unique name and can be identified with this name. 
A level always has a scenegraph-object
*/
class Level
{
public:
    ///The constructor for the level
	/**The level needs a name and cannot exist without a scenegraph-Object which will be generated by the constructor itself
		The user has now a level and a scenegraph with which the user can work from now on*/
	Level(const char* levelName);
	~Level();
	
	///A getter Method which returns a const char
	/**A getter for the name of the level*/
	const char* getLevelName();

	///A getter Method for the scenegraph
	/*Returns the linked scenegraph Object of the level to use its methods*/
	Scenegraph* getScenegraph();

protected:
	const char* m_levelName;
	Scenegraph* m_scenegraph;

private:
	///This method adds a scenegraph to the level
	/**The constructor of "Level" uses this method to add a scenegraph-object automatically*/
	void addScenegraph(Scenegraph* scenegraph);
};

